import * as React from 'react';

class YouTubeEmbed extends React.Component {
  render() {
    return (
      <div style={{ overflow: 'hidden', position: 'relative' }}>
        <iframe

          width="800"
          height="443"
          src="https://www.youtube.com/embed/ah3S2-kK_VU?autoplay=1&fs=0&iv_load_policy=3&showinfo=0&rel=0&cc_load_policy=0&start=0&end=0&vq=hd1080"
          title="YouTube video"
        ></iframe>
        <div
          style={{
            position: 'absolute',
            bottom: '10px',
            left: 0,
            right: 0,
            marginLeft: 'auto',
            marginRight: 'auto',
            color: '#000',
            textAlign: 'center',
          }}
        >
          <div
            style={{
              overflow: 'auto',
              position: 'absolute',
              height: '0pt',
              width: '0pt',
            }}
          >
            Generated by{' '}
            <a href="https://www.embedista.com/embed-youtube-video">Embed Youtube Video</a>{' '}
            online
          </div>
          <script
            type="text/javascript"
            src="https://www.embedista.com/j/ytvideo.js"
          ></script>
        </div>
        <style>
          {`
            .newst {
              position: relative;
              text-align: right;
              height: 420px;
              width: 520px;
            }
            #gmap_canvas img {
              max-width: none !important;
              background: none !important;
            }
          `}
        </style>
      </div>
    );
  }
}

export default YouTubeEmbed;
